spring.application.name=ComputerStore
server.port=8080
spring.sql.init.mode=always
spring.jpa.generate-ddl=true

spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=pyuan
spring.datasource.password=1234

spring.datasource.url=jdbc:postgresql://awseb-e-a6hkqk8zx9-stack-awsebrdsdatabase-v45qy1gb08ko.cz8oi08ecnrg.us-east-1.rds.amazonaws.com:5432/ebdb
spring.datasource.username=postgres
spring.datasource.password=9v6sSAW$%yhMHyiz%yjxS5XOOTBSiIadL8$GQN^KRVNSPJn!vamE&2GFymxb